# Site settings
title: // TODO
email: zach@palumbo.io
description: > # this means to ignore newlines until "baseurl:"
  Check back every day and eventually an actual blog might show up!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "palumbo.io" # the base hostname & protocol for your site
github_username: ParceledTongue
stackexchange_username: DivergentQueries
linkedin_username: zpalumbo

# Build settings
markdown: kramdown
